// .NET --- Coded Tokens
#include "src/CodedTokens/ResolutionScope.c"
#include "src/CodedTokens/TypeDefOrRef.c"
#include "src/CodedTokens/MemberRefParent.c"
#include "src/CodedTokens/HasConstant.c"
#include "src/CodedTokens/CustomAttributeType.c"
#include "src/CodedTokens/HasCustomAttribute.c"
#include "src/CodedTokens/HasFieldMarshal.c"
#include "src/CodedTokens/HasDeclSecurity.c"
#include "src/CodedTokens/HasSemantics.c"
#include "src/CodedTokens/MethodDefOrRef.c"
#include "src/CodedTokens/MemberForwarded.c"
#include "src/CodedTokens/Implementation.c"
#include "src/CodedTokens/TypeOrMethodDef.c"
